exports.replacements = {
  'NONBUDSUPPFINAID': 'Non-budget support in Financial Aid:',
  'PROCOFSERVICES': 'Procurement of Services:',
  'NOTFORPROFITORG': 'Not For Profit Organisations:',
  'MULTILATORGANISATION': 'Multilateral Organisation:',
  'HUMANITASSISTANCE': 'Non-budget support in Financial Aid:',
  'PROCUREMENTOFGOODS': 'Procurement of Goods:',
  'REHABILITATION': 'Rehab:',
  'INFRASTRUCTURE': 'Infrastructure:',
  'SECTORBUDGETSUPPORT': 'Sector Budget Support:',
  'GENBUDGETSUPPORT': 'General Budget Support:',
  'ADMINISTRATION': 'Admin:',
  'MULTISTAKEHOLDER': 'Multistakeholder',
  'OTHERBILATERALDONOR': 'Other',
  'OTHERBILATERALORGANISATION': 'Other bi-lateral orgs:',
  'COMMERCIALIZATION': 'Commercialisation',
  'ACCOUNTABILITY': 'Accountability:',
  'DEFENCEAGAINSTCORRUPTION': 'Defence Against Constructions:',
  'DECENTRALIZATION': 'Decentalisation',
  'DISCLOSURE-iNVESTORS': 'Disclosure to Investors',
  'MULTILATORGNISATION': 'Multilateral Orgs',
  'PROCUREMENTOFSERVICES': 'Procurement of Services',
  'PRCOOFSERVICES': 'Procurement of Services',
  'RECURRENTCOSTS': 'Recurrent Costs',
  'RECONSTRUCTION': 'Reconstruction',
  'UNIVERSALIZATION': 'Universalization'
};